name: 'build-test'

on:
  pull_request:
    branches:
      - main
      - 'releases/*'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Static analysis
        run: npm run check

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

